### ISSUE TITLE
Make sample rate configurable

### ISSUE THREAD

**Issue by blarghmatey** [jlherren/skype-call-recorder#7]
Is it possible to make the sample rate configurable? I would appreciate the possibility of at least setting it to 44.1 kHz to match the sample rate of my microphone when recording podcast interviews.

**Comment by blarghmatey** [comment]
When I attempted to simply change the sample rate constant in the source code and test the result, the recording that was produced was shorter than the actual call and played at an accelerated rate. I'm assuming that to mean that there are other modifications that would be necessary to support a configurable sample rate.

**Comment by jlherren** [comment]
I'd have to check the Skype API again, but last thing I know is that this is not possible at all. The sample rate of the audio stream isn't configured anywhere, it is just received at fixed 16kHz by Skype. That means 16kHz is the sample rate at which Skype records, encodes, transmits, decodes and plays back the audio. There's little that can be done about this (unless it changed in recent years).

Of course you can resample the recordings to 44.1kHz using your favorite audio editor, in order to use them in a 44.1kHz podcast. However you will not gain any acoustic quality this way, since that's all the quality you get from Skype anyway.

But given that Skype started using HD video as well, it's possible that it also started transmitting audio at higher quality and sample rates when possible. But that wouldn't automatically mean that this is also available in the Skype API. Needs to be investigated...

**Comment by blarghmatey** [comment]
Thank you for that background. Time permitting I'll see what I can surface regarding the Skype API, though I'm sure that I'll be limited by the fact that I'm running it on Linux which has not seen much attention from Microsoft and Skype in recent years.
